title: Asontu
description: Tech-blog about T-SQL, C#, Sitecore, JavaScript, Python, Data Science and everything in between run by Herman Scheele
theme: jekyll-theme-hacker
lsi: false
safe: true
source: 
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge