title: Asontu
description: Tech-blog about C#, Sitecore, T-SQL, JavaScript, Python, Data Science and everything in between run by Herman Scheele
theme: jekyll-theme-hacker
author: Herman Scheele

staticman_url: https://asontu-comments.herokuapp.com/v2/entry/asontu-comment-bot/asontu.github.io/master/comments

lsi: false
safe: true
source: 
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge